#!/usr/bin/env bash
#Matthew Page CSCS1240 Spring 2014 Experimenting with some
#bash shell scripting implementation of previous problems

echo "Hello, what is your name?"
read name
echo "Hello" $name

